// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "bt_audio.h"

bool ui_is_loop;
bool ui_is_finish;
bool ui_is_playing;

extern lv_obj_t * lbl_volume_icon;
extern lv_obj_t * lbl_loop;

extern void ui_player_stop_update(void);

void cb_btn_back(lv_event_t *e) {
    lv_scr_load_anim(ui_explorer, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, false);

    ui_is_playing = false;
    ui_player_stop_update();
    lv_label_set_text(ui_lblBtnPlayPause, LV_SYMBOL_PLAY);
    bt_audio_stop();
}

void cb_btn_play_pause(lv_event_t *e) {
    ui_is_playing = !ui_is_playing;

    if (ui_is_playing) {
        lv_label_set_text(ui_lblBtnPlayPause, LV_SYMBOL_PAUSE);

        if(ui_is_finish) bt_audio_seek(0);
        else bt_audio_resume();
    } else {
        lv_label_set_text(ui_lblBtnPlayPause, LV_SYMBOL_PLAY);
        bt_audio_pause();
    }
}

extern esp_err_t ui_audio_prev_track();

void cb_btn_prev(lv_event_t *e) {
    ui_audio_prev_track();
}

extern esp_err_t ui_audio_next_track();

void cb_btn_next(lv_event_t *e) {
    ui_audio_next_track();
}

void cb_btn_loop(lv_event_t *e) {
    ui_is_loop = !ui_is_loop;

    /* Sync vào bt_audio — loop được xử lý nội bộ trong data_cb,
     * không còn đi qua event chain → zero round-trip */
    bt_audio_set_loop(ui_is_loop);

    if (ui_is_loop) {
        lv_obj_set_style_text_opa(lbl_loop, LV_OPA_COVER, 0);
        lv_obj_set_style_text_color(lbl_loop, lv_color_hex(0x4FC3F7), 0);
    } else {
        lv_obj_set_style_text_opa(lbl_loop, LV_OPA_40, 0);
        lv_obj_set_style_text_color(lbl_loop, lv_color_hex(0xFFFFFF), 0);
    }
}

void cb_slider_progress(lv_event_t *e) {
    int pct = lv_slider_get_value(ui_sliderProgress);
    bt_audio_playback_pos_t p = {0};

    bt_audio_get_position(&p);

    uint32_t seek_ms = ((p.duration_ms * pct) / 100) + ((p.duration_ms * pct) % 100);
    bt_audio_seek(seek_ms);

    if (ui_is_finish) {
        ui_is_finish  = false;
        ui_is_playing = true;
        lv_label_set_text(ui_lblBtnPlayPause, LV_SYMBOL_PAUSE);
    }
}

void cb_slider_volume(lv_event_t *e) {
    int vol = lv_slider_get_value(ui_sliderVolume);

    // Đổi icon theo mức volume
    if (vol == 0) {
        lv_label_set_text(lbl_volume_icon, LV_SYMBOL_VOLUME_MID);
    } else if (vol < 50) {
        lv_label_set_text(lbl_volume_icon, LV_SYMBOL_VOLUME_MID);
    } else {
        lv_label_set_text(lbl_volume_icon, LV_SYMBOL_VOLUME_MAX);
    }

    bt_audio_set_volume(vol);
}

extern void ui_bt_start_scan(void);

void cb_rescan_clicked(lv_event_t *e) {
    ui_bt_start_scan();
}
