// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_AUDIOPLAYER_H
#define UI_AUDIOPLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_audioplayer
extern void ui_audioplayer_screen_init(void);
extern void ui_audioplayer_screen_destroy(void);
extern lv_obj_t * ui_audioplayer;
extern lv_obj_t * ui_lblSongName;
extern lv_obj_t * ui_sliderProgress;
extern lv_obj_t * ui_lblTimeElapsed;
extern lv_obj_t * ui_lblTimeTotal;
extern lv_obj_t * ui_btnPlayPause;
extern lv_obj_t * ui_lblBtnPlayPause;
extern lv_obj_t * ui_sliderVolume;
// CUSTOM VARIABLES
extern lv_obj_t * uic_audioplayer;
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

