// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_PanelFileList;
lv_obj_t * uic_ExplorerLabel;
lv_obj_t * uic_explorer;
lv_obj_t * ui_explorer = NULL;
lv_obj_t * ui_ExplorerLabel = NULL;
lv_obj_t * ui_PanelFileList = NULL;
// event funtions

// build funtions

void ui_explorer_screen_init(void)
{
    ui_explorer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_explorer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExplorerLabel = lv_label_create(ui_explorer);
    lv_obj_set_width(ui_ExplorerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExplorerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExplorerLabel, 0);
    lv_obj_set_y(ui_ExplorerLabel, 10);
    lv_obj_set_align(ui_ExplorerLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ExplorerLabel, "File");

    ui_PanelFileList = lv_obj_create(ui_explorer);
    lv_obj_set_width(ui_PanelFileList, 280);
    lv_obj_set_height(ui_PanelFileList, 165);
    lv_obj_set_x(ui_PanelFileList, 0);
    lv_obj_set_y(ui_PanelFileList, 10);
    lv_obj_set_align(ui_PanelFileList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelFileList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelFileList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

    uic_explorer = ui_explorer;
    uic_ExplorerLabel = ui_ExplorerLabel;
    uic_PanelFileList = ui_PanelFileList;

}

void ui_explorer_screen_destroy(void)
{
    if(ui_explorer) lv_obj_del(ui_explorer);

    // NULL screen variables
    uic_explorer = NULL;
    ui_explorer = NULL;
    uic_ExplorerLabel = NULL;
    ui_ExplorerLabel = NULL;
    uic_PanelFileList = NULL;
    ui_PanelFileList = NULL;

}
