// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_EXPLORER_H
#define UI_EXPLORER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_explorer
extern void ui_explorer_screen_init(void);
extern void ui_explorer_screen_destroy(void);
extern lv_obj_t * ui_explorer;
extern lv_obj_t * ui_ExplorerLabel;
extern lv_obj_t * ui_PanelFileList;
// CUSTOM VARIABLES
extern lv_obj_t * uic_explorer;
extern lv_obj_t * uic_ExplorerLabel;
extern lv_obj_t * uic_PanelFileList;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

